"use client";import{useEffect,useState}from"react";import{createClient}from"@/lib/supabase";
export default function Admin(){const s=createClient(),[ok,setOk]=useState(false),[sellers,setSellers]=useState<any[]>([]),[offers,setOffers]=useState<any[]>([]),[msg,setMsg]=useState(""),[p,setP]=useState<any>({brand:"",category:"",name:"",sku:"",image_url:"",reference_price:"",slug:"",description:"",features_text:"",specs_text:"",tiers:"50:0,100:0,250:0,500:0"});
async function load(){const{data:{user}}=await s.auth.getUser();if(!user){location.href="/admin/login";return}const{data:profile}=await s.from("profiles").select("role").eq("id",user.id).single();if(profile?.role!=="admin"){setMsg("Access denied: this account is not an admin.");return}setOk(true);const[{data:a},{data:b}]=await Promise.all([s.from("sellers").select("*").order("created_at",{ascending:false}),s.from("seller_offers").select("*,sellers(business_name),drops(slug,products(brand,name))").order("created_at",{ascending:false})]);setSellers(a||[]);setOffers(b||[])}
useEffect(()=>{load()},[]);
async function seller(id:string,status:string){await s.from("sellers").update({status}).eq("id",id);load()}
async function offer(id:string,status:string){await s.from("seller_offers").update({status}).eq("id",id);load()}
async function createProduct(){setMsg("");const ref=Number(p.reference_price);if(!p.brand||!p.category||!p.name||!p.sku||!p.slug||!ref){setMsg("Brand, name, SKU, slug and reference price are required.");return}const{data:prod,error:pe}=await s.from("products").insert({brand:p.brand,category:p.category,name:p.name,sku:p.sku,image_url:p.image_url||null,reference_price:ref,description:p.description||null,features:String(p.features_text||"").split("\n").map((x:string)=>x.trim()).filter(Boolean),specifications:Object.fromEntries(String(p.specs_text||"").split("\n").map((x:string)=>x.trim()).filter(Boolean).map((x:string)=>{const i=x.indexOf(":");return i>0?[x.slice(0,i).trim(),x.slice(i+1).trim()]:[x,""]})),active:true}).select("id").single();if(pe||!prod){setMsg(pe?.message||"Could not create product");return}const{data:drop,error:de}=await s.from("drops").insert({product_id:prod.id,slug:p.slug,status:"live",starts_at:new Date().toISOString(),ends_at:new Date(Date.now()+7*86400000).toISOString(),commitment_amount:0}).select("id").single();if(de||!drop){setMsg(de?.message||"Could not create drop");return}const rows=String(p.tiers||"").split(",").map((x:string)=>x.trim()).filter(Boolean).map((x:string)=>{const[a,b]=x.split(":");return{drop_id:drop.id,buyer_threshold:Number(a),price:Number(b)}}).filter((x:any)=>x.buyer_threshold>0&&x.price>0);if(rows.length){const{error:te}=await s.from("drop_tiers").insert(rows);if(te){setMsg("Product created, but tier error: "+te.message);return}}setMsg("Product + live TILT created ✓");setP({brand:"",category:"",name:"",sku:"",image_url:"",reference_price:"",slug:"",description:"",features_text:"",specs_text:"",tiers:"50:0,100:0,250:0,500:0"})}
if(!ok)return <div className="authShell"><div className="authCard"><h1>TILT Admin</h1><p>{msg||"Verifying admin access…"}</p>{msg&&<a className="btn" href="/admin/login">ADMIN LOGIN</a>}</div></div>;
return <div className="wrap"><nav className="nav"><a className="logo" href="/">TILT CONTROL</a><span className="tag">ADMIN</span></nav>
<section className="section"><h1>Add product / TILT</h1><div className="card formGrid">{[["brand","Brand"],["category","Category"],["name","Product name"],["sku","SKU"],["image_url","Image URL"],["reference_price","Reference price ₹"],["slug","URL slug"]].map(([k,l])=><label key={k}>{l}<input className="input" value={p[k]||""} onChange={e=>setP({...p,[k]:e.target.value})}/></label>)}<label>Price tiers <input className="input" value={p.tiers} onChange={e=>setP({...p,tiers:e.target.value})}/><small>Format: 50:64999,100:62999,250:59999,500:57999</small></label><button className="btn lime" onClick={createProduct}>CREATE LIVE TILT →</button>{msg&&<p className="notice">{msg}</p>}</div></section>
<section className="section"><h1>Seller approvals</h1><div className="card"><table className="table"><tbody>{sellers.map(x=><tr key={x.id}><td><b>{x.business_name}</b><br/><small>{x.gstin||"GSTIN pending"} · {x.city}</small></td><td>{x.status}</td><td><button className="btn lime" onClick={()=>seller(x.id,"approved")}>APPROVE</button> <button className="pill" onClick={()=>seller(x.id,"rejected")}>REJECT</button></td></tr>)}</tbody></table></div></section>
<section className="section"><h1>Seller bids</h1><div className="card"><table className="table"><tbody>{offers.map(x=><tr key={x.id}><td><b>{x.sellers?.business_name}</b><br/><small>{x.drops?.products?.brand} {x.drops?.products?.name}</small></td><td><b>₹{Number(x.unit_price).toLocaleString("en-IN")}</b><br/>{x.quantity} units</td><td>{x.status}</td><td><button className="btn lime" onClick={()=>offer(x.id,"accepted")}>ACCEPT</button> <button className="pill" onClick={()=>offer(x.id,"rejected")}>REJECT</button></td></tr>)}</tbody></table></div></section></div>}