import Footer from "./Footer";
import ShopBrowser from "./ShopBrowser";
import {createClient} from "@supabase/supabase-js";
const sb=createClient("https://eyboryymmcpwspjxidmk.supabase.co","sb_publishable_n4GU_D-91B2YxLt3O6JqLA_QrwHUChF");
export const revalidate=30;
function money(n:number){return "₹"+Math.round(n||0).toLocaleString("en-IN")}
export default async function Home(){
 const {data}=await sb.from("drops").select("id,slug,status,ends_at,products(id,brand,name,category,reference_price,image_url),drop_tiers(buyer_threshold,price)").eq("status","live").order("created_at",{ascending:false});
 const drops=await Promise.all((data||[]).map(async(d:any,i:number)=>{const {data:s}=await sb.rpc("get_drop_public_stats",{p_drop_id:d.id});const buyers=Number(s?.[0]?.committed_count||0);const tiers=[...(d.drop_tiers||[])].sort((a:any,b:any)=>a.buyer_threshold-b.buyer_threshold);const unlocked=[...tiers].filter((t:any)=>buyers>=t.buyer_threshold).pop();const next=tiers.find((t:any)=>buyers<t.buyer_threshold);const current=Number(unlocked?.price||d.products?.reference_price||0);const pct=next?Math.min(100,Math.round((buyers/next.buyer_threshold)*100)):100;return {...d,buyers,tiers,current,next,pct,accent:["violet","lime","coral"][i%3]}}));
 return <main className="home">
<header className="homeNav"><a className="brand" href="/">TILT<span></span></a><div className="navCenter"><a href="/drops">All drops</a><a href="#how">How it works</a><a href="/seller">For sellers</a></div><div className="navActions"><a className="navGhost navLogin" href="/login">Log in</a><a className="navSignup" href="/register">Sign up</a><a className="navPrimary" href="/dashboard">My TILTs</a></div></header>
<section className="heroXL"><div className="heroNoise"/><div className="heroCopy"><div className="livePill"><span className="pulse"/> LIVE COLLECTIVE COMMERCE</div><h1>THE PRICE<br/>MOVES <em>WITH YOU.</em></h1><p className="heroLead">Join buyers who want the same thing. Commit at the price you would actually pay. More real demand unlocks a better deal for everyone.</p><div className="heroCtas"><a className="ctaPrimary" href="#drops">Explore live TILTs <b></b></a><a className="ctaSecondary" href="/seller">I’m a seller <b>→</b></a></div><div className="trustRow"><span>No fake demand</span><span>1% commitment</span><span>Best unlocked price</span></div></div><div className="tiltVisual"><div className="priceOrb orbA">₹69,990<small>START</small></div><div className="priceOrb orbB">₹62,999<small>UNLOCKED</small></div><div className="priceOrb orbC">₹57,999<small>NEXT TILT</small></div><div className="tiltArrow"></div><div className="visualCaption">more committed buyers<br/><b>push the price down</b></div></div></section>
<section className="marquee"><div>JOIN · COMMIT · SHARE · UNLOCK · SAVE · TILT THE PRICE · JOIN · COMMIT · SHARE · UNLOCK · SAVE · TILT THE PRICE ·</div></section>
<section id="drops" className="dropsSection"><div className="sectionHead"><div><span className="sectionKicker">TRENDING NOW</span><h2>The TILTs people<br/>are watching.</h2></div><div><p>Trending is ranked by real committed demand.</p><a className="viewAllDrops" href="/drops">VIEW ALL DROPS →</a></div></div>
<ShopBrowser drops={[...drops].sort((a:any,b:any)=>b.buyers-a.buyers).slice(0,3) as any[]} showFilters={false}/>
</section>
<section id="how" className="howSection"><div className="howIntro"><span className="sectionKicker">THE MECHANIC</span><h2>Not a coupon.<br/>Not a flash sale.<br/><em>Collective leverage.</em></h2></div><div className="howRail"><div className="howCard"><span>01</span><h3>Name your buy price</h3><p>Tell TILT the maximum price where you are genuinely ready to purchase.</p></div><div className="howCard featured"><span>02</span><h3>Commit 1%</h3><p>Your small commitment turns interest into real buying power. It is adjusted in your final purchase.</p></div><div className="howCard"><span>03</span><h3>Unlock together</h3><p>When more qualified buyers join, sellers can compete for the demand and the price tilts lower.</p></div></div></section>
<section className="sellerStrip"><div><span className="sectionKicker">SELLERS</span><h2>Stop buying clicks.<br/>Bid on ready demand.</h2></div><a href="/seller" className="sellerCta">OPEN SELLER DESK →</a></section>
<Footer/></main>}