"use client";
import {useEffect,useState} from "react";import AdminShell from "../AdminShell";import LoadingOverlay from "../../LoadingOverlay";import {useAdminGuard} from "../useAdminGuard";
export default function DealsAdmin(){const{s,ready,error}=useAdminGuard();const[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[drops,setDrops]=useState<any[]>([]),[offers,setOffers]=useState<any[]>([]),[geo,setGeo]=useState<Record<string,any[]>>({});
async function load(){const[{data:d},{data:o}]=await Promise.all([s.from("drops").select("id,slug,status,starts_at,ends_at,products(brand,name,category),drop_tiers(buyer_threshold,price)").order("created_at",{ascending:false}),s.from("seller_offers").select("*,sellers(business_name),drops(slug,products(brand,name))").order("created_at",{ascending:false})]);setDrops(d||[]);setOffers(o||[]);const ids=[...new Set((o||[]).map((x:any)=>x.drop_id).filter(Boolean))] as string[];const pairs=await Promise.all(ids.map(async id=>{const{data}=await s.rpc("get_drop_geo_summary",{p_drop_id:id});return[id,data||[]] as const}));setGeo(Object.fromEntries(pairs))}
useEffect(()=>{if(ready)load()},[ready]);
async function offerStatus(id:string,status:string){setBusy(true);const{error}=await s.from("seller_offers").update({status}).eq("id",id);setBusy(false);setMsg(error?.message||"Seller bid updated ✓");load()}
async function saveLink(id:string){const row=offers.find(x=>x.id===id);const link=String(row?.payment_link||"").trim();if(link&& !/^https:\/\//i.test(link)){setMsg("Seller payment link must start with https://");return}setBusy(true);const{error}=await s.from("seller_offers").update({payment_link:link||null}).eq("id",id);setBusy(false);setMsg(error?.message||"Seller payment link saved ✓");load()}
if(error)return <div className="authShell"><div className="authCard"><p>{error}</p></div></div>;if(!ready)return <LoadingOverlay label="Verifying admin…"/>;
return <AdminShell title="Deals" subtitle="Monitor deal validity, seller bids and accepted offer payment links.">{busy&&<LoadingOverlay label="Updating deal…"/>}{msg&&<p className="adminMessage">{msg}</p>}<section className="adminPanel"><div className="adminPanelHead"><div><span className="sectionKicker">DEALS</span><h2>All TILTs</h2></div><b>{drops.length}</b></div><div className="adminTableWrap"><table className="table"><tbody>{drops.length?drops.map(d=><tr key={d.id}><td><b>{d.products?.brand} {d.products?.name}</b><br/><small>{d.products?.category||"—"} · /drop/{d.slug}</small></td><td><span className="tag">{d.status}</span></td><td><small>Ends</small><br/>{d.ends_at?new Date(d.ends_at).toLocaleString("en-IN"):"No expiry"}</td><td>{(d.drop_tiers||[]).length} tiers</td></tr>):<tr><td>No deals yet.</td></tr>}</tbody></table></div></section><section className="adminPanel"><div className="adminPanelHead"><div><span className="sectionKicker">SELLER BIDS</span><h2>Offers</h2></div><b>{offers.length}</b></div><div className="adminTableWrap"><table className="table"><tbody>{offers.length?offers.map(x=><tr key={x.id}><td><b>{x.sellers?.business_name}</b><br/><small>{x.drops?.products?.brand} {x.drops?.products?.name}</small><div className="geoSummary">{(geo[x.drop_id]||[]).slice(0,6).map((g:any)=><span key={g.state+"-"+g.city}>{g.city}, {g.state}: <b>{g.buyer_count}</b></span>)}</div></td><td><b>₹{Number(x.unit_price||0).toLocaleString("en-IN")}</b><br/><small>{x.quantity} units</small></td><td>{x.status}</td><td><div className="offerActions"><button className="btn lime" disabled={busy} onClick={()=>offerStatus(x.id,"accepted")}>ACCEPT</button><button className="pill" disabled={busy} onClick={()=>offerStatus(x.id,"rejected")}>REJECT</button>{x.status==="accepted"&&<><input className="input compactInput" placeholder="https:// seller payment link" value={x.payment_link||""} onChange={e=>setOffers(offers.map(o=>o.id===x.id?{...o,payment_link:e.target.value}:o))}/><button className="pill" disabled={busy} onClick={()=>saveLink(x.id)}>SAVE PAYMENT LINK</button></>}</div></td></tr>):<tr><td>No seller bids yet.</td></tr>}</tbody></table></div></section></AdminShell>}
