"use client";
import {useEffect,useState} from "react";
import AdminShell from "../AdminShell";import LoadingOverlay from "../../LoadingOverlay";import {useAdminGuard} from "../useAdminGuard";

const empty={email:"",seller_name:"",store_name:"",company_name:"",gstin:"",seller_category:"",deals_in:"",phone:"",alternate_phone:"",store_address:"",city:"",state:"",pincode:"",website:""};
export default function SellersAdmin(){
 const{s,ready,error}=useAdminGuard();const[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[rows,setRows]=useState<any[]>([]),[sp,setSp]=useState<any>(empty);
 async function load(){const{data}=await s.from("sellers").select("*").order("created_at",{ascending:false});setRows(data||[])}
 useEffect(()=>{if(ready)load()},[ready]);
 function validate(){const req=[["email","Login email"],["seller_name","Seller name"],["store_name","Store name"],["company_name","Company / legal name"],["gstin","GST number"],["seller_category","Seller category"],["deals_in","Deals in"],["phone","Primary phone"],["store_address","Store address"],["city","City"],["state","State"],["pincode","Pincode"]];for(const[k,l]of req){if(!String(sp[k]||"").trim())return l+" is required."}const email=String(sp.email).trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return"Enter a valid seller email address.";const gst=String(sp.gstin).trim().toUpperCase();if(!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(gst))return"Enter a valid 15-character GSTIN.";const phone=String(sp.phone).replace(/\D/g,"");if(phone.length<10||phone.length>15)return"Enter a valid primary phone number.";if(!/^\d{6}$/.test(String(sp.pincode).trim()))return"Enter a valid 6-digit pincode.";return""}
 async function errText(err:any,data:any){if(data?.error)return String(data.error);try{const ctx=err?.context;if(ctx&&typeof ctx.json==="function"){const body=await ctx.json();if(body?.error)return String(body.error)}}catch{}return err?.message||"Could not create seller"}
 async function createSeller(){setMsg("");const v=validate();if(v){setMsg(v);return}setBusy(true);const payload={...sp,email:String(sp.email).trim().toLowerCase(),gstin:String(sp.gstin).trim().toUpperCase(),pincode:String(sp.pincode).trim(),deals_in:String(sp.deals_in).split(",").map((x:string)=>x.trim()).filter(Boolean)};const{data,error}=await s.functions.invoke("admin-create-seller",{body:payload});setBusy(false);if(error||data?.error){setMsg(await errText(error,data));return}setMsg("Seller account created ✓ "+(data?.seller?.store_name||"Seller")+" can now login with OTP.");setSp(empty);load()}
 async function status(id:string,value:string){setBusy(true);const{error}=await s.from("sellers").update({status:value}).eq("id",id);setBusy(false);setMsg(error?.message||"Seller status updated ✓");load()}
 if(error)return <div className="authShell"><div className="authCard"><h1>TILT Admin</h1><p>{error}</p></div></div>;if(!ready)return <LoadingOverlay label="Verifying admin…"/>;
 const fields=[["email","Login email",true],["seller_name","Seller / contact name",true],["store_name","Store name",true],["company_name","Company / legal name",true],["gstin","GST number",true],["seller_category","Seller category",true],["deals_in","Deals in (comma separated)",true],["phone","Primary phone",true],["alternate_phone","Alternate phone",false],["store_address","Store address",true],["city","City",true],["state","State",true],["pincode","Pincode",true],["website","Website",false]];
 return <AdminShell title="Sellers" subtitle="Create seller accounts and control seller access.">{busy&&<LoadingOverlay label="Working…"/>}
  <section className="adminPanel"><div className="adminPanelHead"><div><span className="sectionKicker">NEW SELLER</span><h2>Create seller account</h2></div></div><div className="adminFormGrid">{fields.map(([k,l,r])=><label key={String(k)}>{String(l)}{r&&<span className="requiredMark"> *</span>}<input className="input" type={k==="email"?"email":"text"} inputMode={k==="phone"||k==="alternate_phone"||k==="pincode"?"numeric":undefined} value={sp[String(k)]||""} onChange={e=>setSp({...sp,[String(k)]:k==="pincode"?e.target.value.replace(/\D/g,"").slice(0,6):e.target.value})}/></label>)}</div><button className="btn lime" disabled={busy} onClick={createSeller}>CREATE SELLER ACCOUNT</button>{msg&&<p className="adminMessage">{msg}</p>}</section>
  <section className="adminPanel"><div className="adminPanelHead"><div><span className="sectionKicker">DIRECTORY</span><h2>Seller accounts</h2></div><b>{rows.length}</b></div><div className="adminTableWrap"><table className="table"><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.store_name||x.business_name}</b><br/><small>{x.company_name||""} · {x.gstin||"GST pending"} · {x.city||"—"}</small></td><td>{x.email}<br/><small>{x.phone}</small></td><td><span className="tag">{x.status}</span></td><td><button className="btn lime" disabled={busy} onClick={()=>status(x.id,"approved")}>APPROVE</button> <button className="pill" disabled={busy} onClick={()=>status(x.id,"rejected")}>REJECT</button></td></tr>):<tr><td>No sellers yet.</td></tr>}</tbody></table></div></section>
 </AdminShell>
}